[general]
import = [
    "~/.config/alacritty/themes/themes/solarized_dark.toml"
]

[terminal.shell]
program = "zsh"
args = ["-l", "-c", "zellij"]

[font]
size = 11.0

[font.bold]
family = "Inconsolata"
style = "Bold"

[font.bold_italic]
family = "Inconsolata"
style = "Bold Italic"

[font.italic]
family = "Inconsolata"
style = "Italic"

[font.normal]
family = "Inconsolata"
style = "Regular"
